version: "3.0"

services:
  api:
    build: .
    container_name: go_api
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - go_api_network

  database:
    image: postgres:latest
    container_name: go_api_db
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
    volumes:
      - pg_data:/var/lib/postgres/data
    networks:
      - go_api_network

volumes:
  pg_data:
    driver: local

networks:
  go_api_network:
    driver: bridge
